export interface MovieDetail {
  posterMedium: any;
  title: string;
  year: number;
  addedAt?: string;
  imdb_id: string;
  type: string;
  id: string;
  original_title: string;
  original_language: string;
  Runtime: string;
  us_rating: string;
  release_date: string;
  relevance_percentile: number;
  genres: any;
  genre_names?: string[];
  plot_overview: string;
  runtime_minutes: number;
  end_year: number;
  tmdb_id: number;
  Rated: string;
  Released: string;
  user_rating: string;
  critic_score: string;
  network_names: any;
  backdrop: any;
  trailer: any;
  trailer_thumbnail: any;
}
